### ISSUE TITLE
Dead link to the doc

### ISSUE THREAD

**Issue by scemama** [NLESC-JCER/QMCTorch#149]
Hi, this link in the readme seems dead:
https://qmctorch.readthedocs.io/en/latest/intro.html

**Comment by NicoRenaud** [comment]
should be fixed now

**Comment by tonnylou44853** [comment]
Hi! Unfortunately the 404 error still pops up on my end when I click on the link https://qmctorch.readthedocs.io/en/latest/intro.html.

<img width="909" alt="Screenshot 2023-11-10 at 15 19 03" src="https://github.com/NLESC-JCER/QMCTorch/assets/69238318/08511153-1213-40c1-b4d5-92b232c43fde">

The link https://qmctorch.readthedocs.io/en/latest/ is working though.

**Comment by NicoRenaud** [comment]
Thanks @tonnylou44853 ! Where do you see the dead link (https://qmctorch.readthedocs.io/en/latest/intro.html) ? I can't see it anywhere on the repo

**Comment by tonnylou44853** [comment]
Hi! Sorry that I just realised I misunderstood the problem - I thought the link should be pointing to a webpage instead of being replaced by another link. 

My apologies for the confusion. It is all good now.

**Comment by NicoRenaud** [comment]
Thanks @tonnylou44853 ! No apologies needed, I really appreciate the time you took to look at the code !
